# Generated by Django 5.0.2 on 2024-03-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradus_team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='game_goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='player_goal',
        ),
        migrations.RemoveField(
            model_name='redcard',
            name='game_assist',
        ),
        migrations.RemoveField(
            model_name='redcard',
            name='player_assist',
        ),
        migrations.RemoveField(
            model_name='teamcomposition',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='teamcomposition',
            name='game',
        ),
        migrations.RemoveField(
            model_name='teamcomposition',
            name='team',
        ),
        migrations.RemoveField(
            model_name='yellowcard',
            name='game_assist',
        ),
        migrations.RemoveField(
            model_name='yellowcard',
            name='player_assist',
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.DeleteModel(
            name='Assist',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='RedCard',
        ),
        migrations.DeleteModel(
            name='TeamComposition',
        ),
        migrations.DeleteModel(
            name='YellowCard',
        ),
    ]
