# Generated by Django 5.0.2 on 2024-03-05 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradus_team', '0002_remove_goal_game_goal_remove_goal_player_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_goal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение 1'), django.core.validators.MaxValueValidator(50, 'Максимальное значение 50')], verbose_name='Минута гола')),
                ('game_goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_goal', to='gradus_team.game', verbose_name='Игра')),
                ('player_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_goal', to='gradus_team.player', verbose_name='Автор мяча')),
                ('team_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_goal', to='gradus_team.team', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.ManyToManyField(blank=True, related_name='composition', to='gradus_team.player', verbose_name='Состав команды')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_composition', to='gradus_team.game', verbose_name='Игра')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_composition', to='gradus_team.team', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Состав команды',
                'verbose_name_plural': 'Составы команд',
            },
        ),
    ]
