# Generated by Django 5.0.2 on 2024-03-05 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradus_team', '0003_alter_player_middle_name_goal_teamcomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_assist', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение 1'), django.core.validators.MaxValueValidator(50, 'Максимальное значение 50')], verbose_name='Минута ассиста')),
                ('game_assist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_assist', to='gradus_team.game', verbose_name='Игра')),
                ('player_assist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_assist', to='gradus_team.player', verbose_name='Автор паса')),
                ('team_assist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assist', to='gradus_team.team', verbose_name='Команда')),
            ],
        ),
    ]
