# Generated by Django 5.0.2 on 2024-03-07 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradus_team', '0004_assist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='game_goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='player_goal',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='team_goal',
        ),
        migrations.AlterField(
            model_name='teamcomposition',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_composition', to='gradus_team.team', verbose_name='Команда'),
        ),
        migrations.CreateModel(
            name='GoalAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_goal', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение 1'), django.core.validators.MaxValueValidator(50, 'Максимальное значение 50')], verbose_name='Минута гола')),
                ('game_goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_goal', to='gradus_team.game', verbose_name='Игра')),
                ('player_assist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_assist', to='gradus_team.player', verbose_name='Автор передачи')),
                ('player_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_goal', to='gradus_team.player', verbose_name='Автор мяча')),
                ('team_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_goal', to='gradus_team.team', verbose_name='Команда')),
            ],
        ),
        migrations.DeleteModel(
            name='Assist',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
