# Generated by Django 5.0.2 on 2024-03-08 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradus_team', '0005_remove_goal_game_goal_remove_goal_player_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YellowCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_yellow_card', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимальное значение 1'), django.core.validators.MaxValueValidator(50, 'Максимальное значение 50')], verbose_name='Минута ЖК')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_yellow_card', to='gradus_team.game', verbose_name='Игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_yellow_card', to='gradus_team.player', verbose_name='Игрок')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_yellow_card', to='gradus_team.team', verbose_name='Команда')),
            ],
        ),
    ]
