# Generated by Django 5.0.2 on 2024-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradus_team', '0006_yellowcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='goals_guest_team',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Голов гостевой команды'),
        ),
        migrations.AddField(
            model_name='game',
            name='goals_home_team',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Голов домашней команды'),
        ),
        migrations.AddField(
            model_name='goalassist',
            name='own_goal',
            field=models.BooleanField(default=False, verbose_name='Автогол'),
        ),
    ]
